Social/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),
    name='logout'),
    url(r'signup/$',views.SignUp.as_view(),
    name='signup')
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return "{}".format(self.username)

socialapp/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateform(UserCreationForm):
    class Meta:
        fields=('username','email','password1','password2')
        model=get_user_model()
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Display Name'
        self.fields['email'].label='Email Address'

Social/views.py
from django.views.generic import TemplateView
class HomePage(TemplateView):
    template_name='index.html'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
# Create your views here.
from . import forms
from django.views.generic import CreateView
class SignUp(CreateView):
    form_class = forms.UserCreateform
    success_url = reverse_lazy('login')
    template_name= 'accounts/signup.html'

socialapp/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="btn btn-default" value="Login">
    <p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>

  </form>
  <img src="/static/abc.jpeg" />

</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="container">
  <h1>Sign Up</h1>
  <form method="POST" id="post-form" action="/create_post/">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="btn btn-default" value="Sign Up" id="sign" >

  </form>
  <!--<script>
  console.log(1);

  console.log($('#post-form'))
  $('#post-form').on('submit',function(event){
    event.preventDefault();
    console.log("form submitted!")
    create_post();
  });

</script>-->
  <script src="/static/javascript/main.js"></script>
</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>Social</title>
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

  </head>
  <body>
    <nav class="nav mynav" role='navigation' id='navbar'>
      <div class="container">
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
          <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Log In</a></li>
          <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}


        </ul>

      </div>

    </nav>
    <div class="container mycontent">


    {% block content %}

    {% endblock %}
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome</h1>
{% endblock %}